name: 'movielens'
version: '1.0.0'
config-version: 2

profile: 'movielens-bigquery'


model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"



models:
  movielens: